server:
  port: 8080
  session:
    cookie:
      name: twsession

security:
    basic:
        enabled: false

#facebook:
#  client:
#    clientId: 1761964087358702
#    clientSecret: e09ec7d27145620c6aea7ebcce5d800d
#    tokenName: oauth_token
#    authenticationScheme: query
#    clientAuthenticationScheme: form
#    accessTokenUri: https://graph.facebook.com/oauth/access_token
#    userAuthorizationUri: https://www.facebook.com/dialog/oauth
#  resource:
#    userInfoUri: https://graph.facebook.com/me

logging:
  level:
    org.springframework.security: DEBUG

spring:
  resources:
    chain:
      enabled: true
  messages:
    basename: i18n/messages,i18n/images
  mvc:
    favicon:
      enabled: false